#!/bin/sh

### BEGIN INIT INFO
# Provides:           cr-led-clientd 
# Required-Start:     $network $syslog
# Required-Stop:      $network $syslog
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  CR LED Client 
# Description:  CR LED Client 
### END INIT INFO

# Change the next 3 lines to suit where you install your script and what you want to call it
DIR=/home/pi/Projects/CrimsonRegiment/led-client-deamon/build
DAEMON=$DIR/cr-led-clientd
DAEMON_NAME=cr-led-clientd

# Add and command line options for you daemon here
DAEMON_OPTS=""

# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python
DAEMON_USER=root

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    log_daemon_msg "$DAEMON"
    start-stop-daemon --start --verbose --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --verbose --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

log_daemon_msg "$DAEMON"

case $1 in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0

