#!/bin/bash

ping_node() {
  ping -c 1 -W 1 $1

  if [ $? -ne 0 ]  
  then
    return 1
  fi 
  
  return 0
}

ping_node 192.168.2.9
p9=$?

ping_node 192.168.2.8
p8=$?

ping_node 192.168.2.10
p10=$?

ping_node 192.168.2.11
p11=$?

ping_node 192.168.2.12
p12=$?

ping_node 192.168.2.13
p13=$?

ping_node 192.168.2.14
p14=$?

ping_node 192.168.2.15
p15=$?

printf "\n\nn9: %d  n8: %d  n10: %d  n11: %d  n12: %d  n13: %d  n14: %d  n15:%d\n" $p9 $p8 $p10 $p11 $p12 $p13 $p14 $p15


